---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

library(plotly)

```

```{r read in data and clean}
data("ny_noaa")

ny_noaa_2005 <- ny_noaa %>% 
  separate(date, c("year", "month", "date")) %>% 
  mutate(prcp = prcp/10,
         tmax = as.integer(tmax)/10,
         tmin = as.integer(tmin)/10) %>% 
  filter(snow >= 0,
         year == "2005") # %>% drop_na()
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r compare snowfall and snow depth}
ny_noaa_2005 %>% 
  mutate(snwsd = str_c("Snowfall: ", snow, "\nSnow Depth: ", snwd)) %>%
  rename(snowfall = snow) %>% rename(snowdepth = snwd) %>% 
  plot_ly(
    x = ~snowfall, y = ~snowdepth, color = ~tmin, text = ~snwsd, 
    alpha = .5, type = "scatter", mode = "markers")  
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r look at monthly max temps}
ny_noaa_2005 %>% 
  mutate(month = as.factor(month)) %>% 
  plot_ly(
    y = ~tmax, x = ~month, color = ~month,
    type = "box", colors = "viridis")

```

### Chart C

```{r precipitation over the year, averaged by month}
ny_noaa_2005 %>% 
  drop_na(prcp) %>% 
  group_by(month) %>% 
  summarize(mean_prcp = mean(prcp)) %>% 
  mutate(month = as.factor(month)) %>% 
  plot_ly(
    x = ~month, y = ~mean_prcp, color = ~month, 
    type = "bar", colors = "viridis")
```



